//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roydl.Crypto.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Roydl.Crypto.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ArgumentBitsTypeRatioInvalid {
            get {
                return ResourceManager.GetString("ArgumentBitsTypeRatioInvalid", resourceCulture);
            }
        }
        
        internal static string ArgumentEmpty {
            get {
                return ResourceManager.GetString("ArgumentEmpty", resourceCulture);
            }
        }
        
        internal static string ArgumentSizeTooSmall {
            get {
                return ResourceManager.GetString("ArgumentSizeTooSmall", resourceCulture);
            }
        }
        
        internal static string DirectoryNotFoundDestPath {
            get {
                return ResourceManager.GetString("DirectoryNotFoundDestPath", resourceCulture);
            }
        }
        
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        internal static string InvalidDataCrcValidation {
            get {
                return ResourceManager.GetString("InvalidDataCrcValidation", resourceCulture);
            }
        }
        
        internal static string InvalidOperationUnsupportedType {
            get {
                return ResourceManager.GetString("InvalidOperationUnsupportedType", resourceCulture);
            }
        }
        
        internal static string NotSupportedStreamRead {
            get {
                return ResourceManager.GetString("NotSupportedStreamRead", resourceCulture);
            }
        }
    }
}
